source 'http://rubygems.org'

gem 'prawn', '0.11.1'
gem 'pg'
gem 'fleximage', '1.0.4'
gem 'RedCloth'
gem 'pdfkit'
gem 'rails', '3.0.6'
#gem 'rails', '2.3.5'
gem 'capistrano', '2.12.0'
gem 'mime-types', '1.23'
gem 'mysql'
gem 'rdoc'
gem "activemerchant", "1.5.1"
gem 'will_paginate', '>= 2.3.12'
gem 'require_relative'
gem 'sshkit'
gem 'rvm-capistrano'
gem 'rake', '~> 0.8.7'
gem 'debugger'
gem 'better_nested_set'
gem 'rmagick', :require => false
gem 'simple_captcha', :git => 'git://github.com/galetahub/simple-captcha.git'
