
development:
  adapter: mysql2
  database: italyabroad_stg
  username: root
  password: glogics123  
#  socket: /var/mysql/mysql.sock

test:
  adapter: mysql2
  database: italyabroad_test
  username: root
  password: password


#  socket: /var/mysql/mysql.sock

#production:
#  adapter: mysql2
#  encoding: utf8
#  host: 89.145.121.178
#  port: 80
#  database: italy2011sep_prod
#  username: root
#  password: italyabroad

production:
  adapter: mysql2
  database: italyabroad_production
  encoding: utf8
  username: root
  password: italyabroad

staging:
  adapter: mysql2
  database: italy_april_production
  username: root
  password: italyabroad

nov18:
  adapter: mysql2
  database: italyabroad_production_18Nov2014
  username: root
  password: italyabroad
